add tablestructure
MarcRaeder/HTML-Table pull request #1
Opened 2022-09-08 08:35 UTC by MarcRaeder

2022-09-08 12:39 UTC, stefanluth commented
`table.js` is empty, and no PR description :)

2022-09-09 06:13 UTC, DevBastiS requested changes
Also what @stefanluth said.

2022-09-09 06:13 UTC, DevBastiS commented on table.css
> +.table__headerRow {
```suggestion
.table__header-row {
```

Apply this to all css classes please.

2022-09-09 06:13 UTC, DevBastiS commented on table.html
> +
```suggestion
```

2022-09-09 06:13 UTC, DevBastiS commented on table.html
> +
```suggestion
```

2022-09-14 06:35 UTC, DevBastiS requested changes

2022-09-14 06:35 UTC, DevBastiS commented on table.css
> +}
```suggestion
.table__header-row {
  background-color: goldenrod;
  height: 50px;
}

.table__content-row {
  border: 1px solid black;
  text-align: center;
}

.table__header-row-body {
  border: 1px solid black;
}

.table__content-row-body {
  border: 1px solid black;
}
```

2022-09-14 06:45 UTC, MarcRaeder commented
> `table.js` is empty, and no PR description :)

yes but is only the BASIC Structure. And this includes the .js file

2022-09-14 06:53 UTC, stefanluth approved these changes

2022-09-15 06:06 UTC, DevBastiS approved these changes
Please fix these changes then merge.

2022-09-15 06:06 UTC, DevBastiS commented on table.html
> +  <script> scr = "table.js"</script>
```suggestion
  <script> scr="table.js"</script>
```

2022-09-15 06:06 UTC, DevBastiS commented on table.html
> +        <td class="table__content-row-body">Bob</td>
Sorry I should have seen that earlier:
```suggestion
        <td class="table__content-row-cell">Bob</td>
```

2022-09-15 06:06 UTC, DevBastiS commented on table.html
> +        <td class="table__content-row-body">Bob</td>
This is a cell of the table not a body. You could argue that "table__cell" would suffice too.

2022-09-15 06:55 UTC, merged