add Show/hide data
MarcRaeder/HTML-Table pull request #2
Opened 2022-09-15 07:15 UTC by MarcRaeder

Add Show/Hide Data Function

2022-09-16 06:32 UTC, DevBastiS requested changes

2022-09-16 06:32 UTC, DevBastiS commented on table.js
> +function CheckIfShowOrHide(columnData) {
This function does not only check if the elements should be hidden or not it is also hiding them. Please use a more speaking name.

2022-09-16 08:26 UTC, stefanluth requested changes

2022-09-16 08:26 UTC, stefanluth commented on table.js
> +function ShowHide(columnClass) {
Functions should be camelCase :)

2022-09-20 07:39 UTC, stefanluth approved these changes

2022-09-21 05:59 UTC, DevBastiS approved these changes

2022-09-21 13:33 UTC, merged