Add Change columnsize
MarcRaeder/HTML-Table pull request #3
Opened 2022-09-21 13:38 UTC by MarcRaeder

Add Change columnsize feature

2022-09-21 14:35 UTC, stefanluth requested changes

2022-09-21 14:35 UTC, stefanluth commented on table.js
> +    var mouseend = event.clientX;
camelCase :)

2022-09-21 14:35 UTC, stefanluth commented on table.js
> +    var leftborder = leftColumnWidth < minWidth && event.clientX >= (previousColumsWidth + minWidth);
camelCase :)

2022-09-21 14:35 UTC, stefanluth commented on table.js
> +    var rightborder = rightColumnWidth < minWidth && event.clientX <= (previousColumsWidth + leftColumnWidth + minWidth);
camelCase :)

2022-09-21 14:35 UTC, stefanluth commented on table.js
> +  const mousestart = event.clientX;
camelCase :)

2022-09-21 14:35 UTC, stefanluth commented on table.js
> +function dragstart(event, borderNumber) {
camelCase :)

2022-09-21 14:35 UTC, stefanluth commented on table.js
> +  function mousemove(event) {
camelCase :)

2022-09-27 14:11 UTC, matthiasdanne requested changes
What Stefan said

2022-09-27 14:19 UTC, DevBastiS commented
What Stefan said

2022-10-04 09:24 UTC, stefanluth approved these changes

2022-10-04 09:24 UTC, stefanluth commented on table.css
> +
```suggestion
```

2022-10-04 09:36 UTC, DevBastiS approved these changes

2022-10-04 09:37 UTC, merged